# Generated by Django 4.1.5 on 2023-01-25 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorek_pogody", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lokalizacja",
            old_name="szerkosc",
            new_name="szerokosc",
        ),
    ]
