# Generated by Django 4.1.5 on 2023-01-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("monitorek_pogody", "0002_rename_szerkosc_lokalizacja_szerokosc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lokalizacja",
            name="obiektGeograficzny",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lokalizacja",
                to="monitorek_pogody.obiektgeograficzny",
            ),
        ),
    ]
