# Generated by Django 4.1.5 on 2023-01-25 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorek_pogody", "0003_alter_lokalizacja_obiektgeograficzny"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="lokalizacja",
            unique_together={("szerokosc", "dlugosc")},
        ),
    ]
