# Generated by Django 4.1.5 on 2023-01-25 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("monitorek_pogody", "0004_alter_lokalizacja_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="pogoda",
            unique_together={("lokalizacja", "dataPomiaru")},
        ),
    ]
