# Generated by Django 4.1.5 on 2023-01-25 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorek_pogody", "0005_alter_pogoda_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pogoda",
            name="fazaKsiezyca",
            field=models.CharField(
                choices=[
                    ("pierwsza kwadra", "Pierwszakwadra"),
                    ("now", "Now"),
                    ("ostatnia kwadra", "Ostatniakwadra"),
                    ("pełnia", "Pelnia"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="pogoda",
            name="jakoscPowietrza",
            field=models.CharField(
                choices=[
                    ("bardzo dobre", "Bardzodobre"),
                    ("dobre", "Dobre"),
                    ("umiarkowane", "Umiarkowane"),
                    ("złe", "Zle"),
                    ("bardzo złe", "Bardzozle"),
                ],
                max_length=255,
            ),
        ),
    ]
