# Generated by Django 4.1.5 on 2023-01-25 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorek_pogody", "0006_alter_pogoda_fazaksiezyca_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pogoda",
            name="fazaKsiezyca",
            field=models.CharField(
                choices=[
                    ("pierwsza kwadra", "Pierwszakwadra"),
                    ("nów", "Now"),
                    ("ostatnia kwadra", "Ostatniakwadra"),
                    ("pełnia", "Pelnia"),
                ],
                max_length=255,
            ),
        ),
    ]
