# Generated by Django 4.1.5 on 2023-01-25 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("monitorek_pogody", "0007_alter_pogoda_fazaksiezyca"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pogoda",
            name="dataPomiaru",
            field=models.DateTimeField(),
        ),
    ]
